### PR TITLE
Adds conversion for vectors

### PR DESCRIPTION
**Pull request by ankane**
For #148

For `From_Ruby`, was wondering if there's a way to avoid copies.

Also, if it's easier to update than give feedback, feel free.

Edit: The three test failures are unrelated.

### CODE REVIEW

**Comment by cfis** [comment]
This approach definitely works, but the issues, as you point out,  is that it copies data between Ruby and C++. Besides whatever cost that might have, dependent on the element type, it also results in the vectors effectively becoming readonly (changes in Ruby aren't seen in C++ and vice versa). 

The other way is to keep a vector a vector under the hood - just directly store it. Pybind11 supports both ways - see https://pybind11.readthedocs.io/en/stable/advanced/cast/stl.html.

I prefer approach #2. What I have partially implemented (but not checked in) is equivalent to PyBind11's `PYBIND11_MAKE_OPAQUE` macro and then `py::bind_vector<std::vector<int>(m, "VectorInt")`. What I don't like about they PyBind11 solution is having to define what std::vector's you want (and maps, and unordered_maps, set, unordered_set, etc).

What would be better in my view is auto defining the right stl containers. To do that I've been putting in the foundation to do more aggressive, and flexibly, type verification at runtime (or even better compile time). So when define_method is executed (or compiled), Rice iterates over its parameters and return value and calls a method asking if the type has been registered with Rice. If not, then the default is throw an exception. But that templated method can be overridden - and the vector code would just auto define the vector instead of throw an exception.

That will look a bit like how Enum's currently work. So add a `define_vector<T>` call, which then creates a class with a bunch of vector methods (`size`, `[]`, etc) and binds that to `Data_Vector<std::vector<T>>`.

**Comment by ankane** [comment]
Ah, interesting. From the link, it looks like pybind11 uses `stl.h` to copy and `stl_bind.h` + `PYBIND11_MAKE_OPAQUE
` to keep them synced. What do you think about supporting both patterns? I haven't run into a need for the bind pattern, but could use the copy pattern in a number of projects.

**Comment by cfis** [comment]
I prefer the "wrap" pattern over the copy pattern for a few reasons:

* It can be much more performant
* Doesn't have the surprise that modifications made in Ruby don't flow through to C++
* Consistent with how the rest of Rice works - your wrap C++ classes instead of copying them (say you have a std::vector<MyClass> - why would the vector be copied but not MyClass?

And if you want to make a copy, it would be easy to do in ruby:

````ruby
array = Array.new
some_vector.each do |value|
  array << value
end
```
Or roll your own To_Ruby/From_Ruby like you have done.

I'm guessing PyBind11 enables both ways, because it can automatically support the copy case but the user has to do extra work for the wrap case. But having two ways seems confusing to me - and if we can make the wrap cause automatically work I think that's the way to go.

**Comment by ankane** [comment]
It seems like this mainly affects the `To_Ruby` case, since `From_Ruby` will always need to copy when converting a Ruby array to `std::vector`.

I think it'll be more common for Rice users to want methods to return a standard Ruby array rather than a custom Rice object (at least this is the case for my projects), which makes it a better default in my view.

However, as you mention, it'll be possible for users to do this on their own if it's not the default.

**Comment by cfis** [comment]
You could skip From_Ruby by creating a vector of the required type to pass to a C++ api.

But I agree there should have a default implementation of To_Ruby for converting anything enumerable on the Ruby side to a vector.

A wrapped vector could (should) have the same api as a Ruby Array, so from the Ruby side there wouldn't be any difference programming against a vector or an array.

**Comment by ankane** [comment]
Will close this out

**Comment by cfis** [comment]
@ankane - I just pushed changes to master that wrap std::vectors so they look like Ruby arrays. Still need to add a From_Ruby method so that Ruby array's get converted to vectors. I'll grab the code you pushed to do that if that's ok.

**Comment by ankane** [comment]
Yeah, definitely

**Pull request closed without merging**
