### PR TITLE
add support for experimental filesystem - fixes jasonroelofs/rice/197

### PR DESCRIPTION
**Pull request by thekendalmiller**
Fixes https://github.com/jasonroelofs/rice/issues/197

This works on Ubuntu 22.04 and Amazon Linux 2. 
I _believe_ `__has_include` was added in c++17

### CODE REVIEW

**Comment by jasonroelofs** [comment]
A quick search about `__has_include` and I believe you're right. This looks good, thanks for tracking this down!

**Comment by thekendalmiller** [comment]
@jasonroelofs Thanks for the help with this. Is there any ETA of when you'll release the next gem version with this fix? 

I haven't been able to get bundler to play nice with a gem installed from git and a gem installed from ruby gems. I am encountering something similar to https://github.com/rubygems/rubygems/issues/5249. The issue description and analysis might be wrong because installation order does work out or `rice` and `mini_portile` and similar gems would fail if not. I think It's because one gem is from rubygems and one is from git and bundler/ruby gems puts them in separate locations and the `require mkmf-rice` fails, presumably because the $LOAD_PATH doesn't include the git sourced gems.

**Comment by jasonroelofs** [comment]
Yeah I can cut a release. I'll get something out this weekend.

**Comment by jasonroelofs** [comment]
Rice 4.2.1 is out with this change.

**Pull request merged**
