### PR TITLE
Added Ruby 3.2 to CI

### PR DESCRIPTION
**Pull request by ankane**
Has same issue as Ruby 3.1 (#167)

### CODE REVIEW

**Comment by ankane** [comment]
Looks like 3.2 isn't available with `setup-ruby` on Windows yet - will follow up when it is.

**Comment by jasonroelofs** [comment]
Thanks for jumping on this. I'll keep an eye on setup-ruby as well.

**Comment by ankane** [comment]
It's now available: https://github.com/ruby/setup-ruby/releases/tag/v1.132.0

**Comment by ankane** [comment]
Looks like a destructor test is falling in one spot, but passes in others:

```text
Failures:

Data_Object:ruby_custom_free: Assertion failed: true != test_destructor_called (1 != 0) at test_Data_Object.cpp:213
```

Could be similar to https://github.com/jasonroelofs/rice/blob/594e49e876948075e2c641d1d1f28c72485e4032/test/test_Self.cpp#L165-L166

**Comment by jasonroelofs** [comment]
Re-running the Windows test, see if it's a flake or if we need to tweak something.

**Comment by cfis** [comment]
Looks like 3.2 is now supported. There is a test failure like you mentioned, but thinking that should be dealt with in a separate issue? So I went ahead ahead and merged this.

**Comment by jasonroelofs** [comment]
Thanks, yeah it's a weird test that may be flaky, only on windows and to do with GC-triggered deconstructors. I don't have an easy way of checking this out locally right now, though it does seem to be consistent (master is red for the same reason).

I should get a Windows setup running so I can do something here.

**Comment by cfis** [comment]
I have windows setup (mswin and mingw) so can take a look.

**Pull request merged**
