### PR TITLE
Revamp wrapping native functions

### PR DESCRIPTION
**Pull request by cfis**
This is a much more significant pull request. It revamps how native functions are wrapped. It removes the auto-generated code in Auto_Function_Wrapper and Auto_Member_Function_Wrapper and replaces it with a generic implementation in Wrapper_Function (see new Wrapper_Function.ipp file).

It does this by introducing two new ideas - a Receiver_T template typename in Wrapper_Function and the use of std::apply. 

Receiver_T is the receiver of the native function call. It can have 4 classes of values:
   * std::null_ptr - There is no receiver, this is for a stand-alone function or static member function (replaces  Auto_Function_Wrapper)
   * C++ Object - This is the most common value and is used to invoke a member function 
     on a wrapped instance of a C++ object (replaces Auto_Member_Function_Wrapper)
   * Object - This is used by Rice for calling Rice::Constructor (previously supported by special case in Auto_Function_Wrapper)
   * Class - This is used for Rice for translating enums values (previously supported by special case in Auto_Function_Wrapper).

std::apply is used to call the wrapped native function with an arbitrary number of arguments (thus removing the need to special case Arg0, then Arg0/Arg1, then Arg0/Arg1/Arg2, etc.).

NOTE - This pull request requires the use of C++17 due to the use of std::apply and "if constexpr (..)". To compile using autoconf you need to update configure.ac line 25 to:

AX_CXX_COMPILE_STDCXX(17, noext, mandatory)

Thus the previous commit to update the m4 macro to support C++17.

If moving to C++17 is a deal breaker then this can be made to work with C++14. To do so would require:

* Including a backported version of std::apply in the source tree. For example - [https://github.com/martinmoene/invoke-lite](https://github.com/martinmoene/invoke-lite).

* For getReceiver create 4 overrides, one for each Receiver_T. Select the correct one using enable_if and SFINAE.

* For invokeNative create 2 overrides,  one for void Return_T and one for all other Return_T. Select the correct one using enable_if and SFINAE.

### CODE REVIEW

**Comment by jasonroelofs** [comment]
This is cool stuff! Going to spend some time making sure I understand what's going on with these changes, and will ask about anything that isn't quite clear, but I like getting rid of the auto-gen code, and I'm not against pushing up to a C++17 minimum, I just don't know how many users of Rice will have a problem with that.

**Comment by cfis** [comment]
Happy to answer any questions you have - maybe annotate the pull request?

One thing I should have mentioned - the number or arguments (Arg_Ts...) is equal to the number of arguments sent by Ruby in argc and argv. 

In the case where Receiver_T is nullptr or a C++ object then the native function takes the same number of arguments. If the Receiver_t is a Rice Object (for constructor) or Rice Class (for Enums) then the native function takes sizeof...(Arg_Ts) + 1 - we tack on the Object or Class at the beginning. Note that we actually also tack on the C++ instance object (ie., this), but std::apply uses that to determine what object to send the function call to - the function itself of course does not take a this parameter.

**Comment by jasonroelofs** [comment]
Let me know if you need help with the Mac build. I haven't seen anything that jumps out as confusing, but haven't given it a fully detailed look through yet. I want to get a new release out soon with the other things so I'll hold off on merging this until that release is out.

Thanks again for all of your contributions! I've been out of the C++ world for a while now, it's cool to see what the language is able to do now.

**Comment by cfis** [comment]
Ah - wasn't sure if the Mac build was supposed to work or not. But I can take a look.

Not to overwhelm you, but I have a series of additional commits after this one. See https://github.com/cfis/rice/commits/dev.

Sounds like a good idea to get a new release out first.

**Pull request closed without merging**
