### PR TITLE
Sphinx docs

### PR DESCRIPTION
**Pull request by jasonroelofs**
This PR converts our documentation system from Doxygen to Sphinx Docs, and splits out our massive single-file README into a nested structure.

I looked through a few themes on https://sphinx-themes.org/ and found Furo as one I liked. It's clean, simple, and isn't obviously Sphinx or ReadTheDocs.

With this PR we will close out #152 and move that discussion here. Still to document:

- [x] Migration from `to_ruby`/`from_ruby` to the new struct.
- [x] `define_function` / `define_singleton_function` vs `define_method` / `define_singleton_method` and `self`
- [x] `Return().takeOwnership()` and ownership rules
- [x] `Arg.keepAlive`
- [ ] `stl.hpp` and the caveats of STL support.

Tutorial - Rice documentation 2021-04-10 12-12-36

### CODE REVIEW

**Comment by jasonroelofs** [comment]
Realizing that I did not pull master lately so this does not yet include your most recent docs updates @cfis. Will fix that.

**Comment by jasonroelofs** [comment]
Ok I think my docs are up-to-date with the latest on master.

**Comment by cfis** [comment]
An nice!  Thanks for doing this.

Some quick thoughts. Under Tutorial on the left, could it show the subtopics "Getting started", "Defining Method", etc? Basically the headers that already exist in the Tutorial page. Right now instead the visible subtopics (like Memory Management) aren't actually part of the tutorial.

Then on the left under tutorial add a new top level topic called something like  "Advanced" or "Reference"? Then under that would go Memory Management, Adding Type Converts, etc. 

Then another topic on the left, Standard Template Library?  I was going to start writing that up...although probably not until a little later this week.

**Comment by jasonroelofs** [comment]
Applied much of what you suggested, and added a page for the STL documentation. Still need to set up a section for the 3 -> 4 Migration but overall this is looking nice. I'll probably merge this today and get it deployed so we can read through and update quickly.

**Comment by jasonroelofs** [comment]
I've added an initial Migration doc and did a pass of all the docs to make sure links work and everything is consistently styled.

**Comment by cfis** [comment]
Looks great, thanks for adding the migration document. I can add a what's new section too...you already mentioned the single header file, but some things like attribute support, partial stl support, etc.

**Pull request merged**
