### PR TITLE
Header only library

### PR DESCRIPTION
**Pull request by jasonroelofs**
This is mainly an experiment to see if Rice can be migrated to a header-only gem, much in the way of pybind11. Doing so would solve a number of build problems, mainly the issue around static vs dynamically built Ruby.

So far a lot of the pieces moved over fine, but the core structure around Object, Module, Array, and String need some effort to re-think the dependency graph, and may require some API breakage.

If this works out, it will be released as Rice 3.

### CODE REVIEW

**Comment by ankane** [comment]
This sounds great. Happy to test with a few projects if it gets to a good spot.

**Comment by cfis** [comment]
Agreed this looks great - any additional progress?

**Comment by jasonroelofs** [comment]
Man has it been that long since I last looked at this? So once I got through all of the easy pieces, it quickly became apparent that to get the core of Rice functional with a header-only setup was going to require significant re-think of how the library works, and as I haven't actually used Rice for anything for quite some time, I can't say I'm really motivated to put in that effort for an unknown pay-off. If someone else is interested in picking up this PR and pushing it forward I'm happy to support that, but for now I won't be doing anything more here.

**Comment by cfis** [comment]
Makes sense. I might try to give it a go, but surely will need some pointers from you!

**Comment by cfis** [comment]
See #146.

**Comment by ankane** [comment]
This is really great @cfis! Will try it out on a few of my gems and let you know how it goes.

**Comment by cfis** [comment]
@ankane - That would be great. Running through some real world examples would be fantastic.

Note that the updated version of Rice isn't 100% backwards compatible - although its pretty close. So it should be easy to update code but I do plan on adding a migration paragraph to the documents. 

It would be very helpful if you can open any tickets for any issues you run into.

**Comment by jasonroelofs** [comment]
Well this PR, my quite old initial WIP, can be closed!

**Pull request closed without merging**
